baseURL: /
languageCode: en-us
build:
  writeStats: true
params:
  title: FABLAB | UA
  author: Dmitri Senchuk
  description: Website title
  copyright: >-
    powered by [hugo](https://gohugo.io/)
  theme:
    mainTheme: light
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Dmitri Senchuk"
    tagline: "21"
    location: "Kyiv, Ostriv"
    photo: myphoto1.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "#"
        title: LinkedIn
      - icon: fab fa-stack-overflow
        url: "#"
        title: StackOverflow
      - icon: fab fa-github
        url: "https://github.com/s8/FabAcademyUA_2024_Ostriv/tree/main/Dmitri_Senchuk"
        title: GitHub
      - icon: fab fa-twitter
        url: "#"
        title: Twitter
      - icon: fab fa-orcid
        url: "#"
        title: Orcid
      - icon: ai ai-google-scholar
        url: "#"
        title: Google Scholar
      - icon: fab fa-researchgate
        url: "#"
        title: ResearchGate
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: Hello, as you know, my name is Dmitry and I have a long-standing passion for technology, 
      engineering and construction. This interest has been nurtured by my family members since early childhood, and my home is a continuous workshop in which I grew up. 
      During my studies, I was an active member of the engineering club, where I helped to modernize CNC machines and 3D printers. I also volunteered and represented my college at various events.
      Now I am studying at the National Aviation University. There, I lead a team of engineering students
      who work on renewable energy and 3D printing. I also attend various additional lectures and events 
      related to science, technology, cybersecurity, first aid training, etc.
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Software engineer
        dates: 10/2022 - 02/2023
        company: Metal Center LLC
        details: >-
          While holding this position and additionally taking on the duties of
          design engineer, I managed to optimize and improve the quality of work
          of the enterprise by learning an additional program for cutting parts on my own
          CypNest, which significantly reduced the number of errors and
          saving me time on correcting employee schedules. When communicating with
          customers, it is clear that these changes have had a very positive impact on
          regular and new clients, to whom we provided much better documentation,
          which, in turn, also affected the company's competitiveness,
          because a client does not want to proofread a large amount of hard-to-understand documentation and waste time. Thus, making a monthly report on the work of the site,
          industrial laser, saved me time and the work of the accounting department. During the
          During my work, I had to meet the challenges or improve the welfare of the
          of the team, the work and arrangement of the site, and the modernization of equipment, including
          This also includes the development of hinged mounts for equipment, a ventilation system
          and its installation, a stove to improve the working conditions of the team in winter.
      - position: CNC operator
        dates: 06/2020 - 09/2022
        url: "https://www.aton.ua/en/"
        company: Aton LLC
        details: >-
          He also worked during internships and vacations. Writing programs for
          bending machine, bending parts, checking the quality according to
          documentation and drawings. Optimization of work for transporters,
          sorting and arranging pallets in a way that saves maximum time
          for their delivery to another workshop, machine maintenance and workplace maintenance.
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:      
      - degree: B.S. in Subject
        college: National Aviation University
        dates: 2023 - *Present*
        thesis_title: "Faculty of Air Navigation, Electronics and Telecommunications,
        Department of Aviation Computer Integrated Complexes.
        Specialty 174 Automation, Computer-integrated technologies and robotics. 
        Training program Information technologies and engineering of 
        aviation computer system."
        thesis_url: "https://nau.edu.ua/en/"
      - degree: Associate degree 
        college: Khmelnytskyi Polytechnic Professional College
         by "National Lviv University Polytechnic."
        dates: 2018 - 2022
        thesis_title: "Department Engineering Mechanics, 
        131 Applied Mechanics. received the qualification
        of Electromechanic in the field of Mechanical Engineering."
        thesis_url: "https://hpk.edu.ua/en/home/golovna-storinka"
  publication:
    title: Publications
    icon: fas fa-book
    format:
      - date
      - title
      - authors
      - journal
    types:
      - Journal Articles
      - Proceedings
    list:
      - title: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.
        authors: "F Last, F Second, P secondary"
        date: "2018"
        journal: "Journal of Field 52 (16), 9033-9044"
        url: "#"
        type: Journal Articles
      - title: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.
        authors: "F Last, F Second, P secondary"
        date: "2018"
        journal: "Journal of Field 52 (16), 9033-9044"
        url: "#"
        type: Journal Articles
      - title: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.
        authors: "F Last, F Second, P secondary"
        date: "2018"
        journal: "Journal of Field 52 (16), 9033-9044"
        url: "#"
        type: Proceedings
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: ShpakUA
        url: "#"
        description: The project aims to help Ukrainian citizens and foreigners
        get to safety in the context of the war with Russia, which is using its
        air force to bomb residential areas.
      - title: Project 2
        url: "#"
        description: Description of the project
      - title: Project 3
        url: "#"
        description: Description of the project
      - title: Project 4
        url: "#"
        description: Description of the project
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "Skill 1, Skill 2"
        skillrating: 90
      - skill: Skill 3
        skillrating: 80
      - skill: Skill 4
        skillrating: 50
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Robotics
      - hobby: Avionics
      - hobby: Hiking
      - hobby: Ping Pong
      - hobby: Martial arts
